[workspace]
resolver = "2"
members = ["protocol-minimal", "bench", "source-cli", "demo-server", "journalist-cli"]

# Crates use version.workspace for consistency.
[workspace.package]
name = "securedrop-protocol"
version = "0.4.0"
edition = "2024"
authors = ["SecureDrop Team <securedrop@freedom.press>"]
license = "GPL-3.0"

[workspace.dependencies]
# Crypto stack (must be kept in sync with hax-lib):
hpke-rs = "0.7.0"
libcrux-ed25519 = "0.0.9"
libcrux-curve25519 = "0.0.8"
libcrux-chacha20poly1305 = "0.0.9"
libcrux-traits = "0.0.8"
libcrux-kem = "0.0.9"
libcrux-ml-kem = "0.0.10"
libcrux-sha2 = "0.0.8"
libcrux-hkdf = "0.0.8"

hax-lib = "0.3.7"

# Everything else:
anyhow = "1.0"
axum = "0.7"
bip39 = { version = "2", default-features = false }
clap = "4"
criterion = "0.5"
directories = "6"
getrandom = { version = "0.3", default-features = false }
hashbrown = "0.14"
hex = { version = "0.4", default-features = false }
js-sys = "0.3"
proptest = "1.11"
rand = "0.10"
rand_chacha = { version = "0.10.0", default-features = false }
rand_core = "0.10"
reqwest = { version = "0.12", default-features = false }
serde = { version = "1", default-features = false }
serde_json = { version = "1", default-features = false }
tokio = "1"
uuid = { version = "1.0", default-features = false }
wasm-bindgen = "0.2.121"

# exact version is pinned to avoid forced updates to wasm-bindgen.
wasm-bindgen-test = "=0.3.71"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(hax)"] }
