#!/bin/sh
set -eu

# Write autogenerated targets to targets.mk.
# Requires rust nightly toolchain.
# Uses hir-tree to find uses of libcrux uses and  

OUT=targets.mk

tmp="$(mktemp)"

CRYPTO_CRATE="${1:?usage: $0 <crate-name>}"

cat > "$tmp" <<'EOF'
# AUTOGENERATED. DO NOT EDIT. Manual edits belong in the Makefile.
# Regenerate with: 'make update-targets'

EOF

cargo +nightly rustc -- -Zunpretty=hir-tree \
| rg -o "DefId\([^)]*${CRYPTO_CRATE}[^)]*" \
| sed -E 's/.*~ //' \
| sed -E 's/\[[^]]*\]//g' \
| sed -E 's/::\{constructor#.*$//' \
| rg '::' \
| sort -u \
| awk '
{
    lines[NR] = $0
}

END {
    for (i = 1; i <= NR; i++) {
        keep = 1

        for (j = 1; j <= NR; j++) {
            if (i == j)
                continue

            # Drop if another target is a more specific child
            if (index(lines[j], lines[i] "::") == 1) {
                keep = 0
                break
            }
        }

        if (keep)
            print lines[i]
    }
}
' \
| awk '
{
  target = $0

  if ($0 ~ /^libcrux_ecdh::/)
    var = "LIBCRUX_ECDH_TARGETS"
  else if ($0 ~ /^libcrux_kem::/)
    var = "LIBCRUX_KEM_TARGETS"
  else if ($0 ~ /^libcrux_ml_kem::/)
    var = "LIBCRUX_ML_KEM_TARGETS"
  else if ($0 ~ /^libcrux_traits::/)
    var = "LIBCRUX_TRAITS_TARGETS"
  else if ($0 ~ /^libcrux_curve25519::/)
    var = "LIBCRUX_CURVE25519_TARGETS"
  else if ($0 ~ /^libcrux_chacha20poly1305::/)
    var = "LIBCRUX_CHACHA20POLY1305_TARGETS"
  else
    next

  print var " += +" target
}
' >> "$tmp"

mv "$tmp" "$OUT"