# AUTOGENERATED. DO NOT EDIT. Manual edits belong in the Makefile.
# Regenerate with: 'make update-targets'

LIBCRUX_CHACHA20POLY1305_TARGETS += +libcrux_chacha20poly1305::impl_hacl::decrypt
LIBCRUX_CHACHA20POLY1305_TARGETS += +libcrux_chacha20poly1305::impl_hacl::encrypt
LIBCRUX_CHACHA20POLY1305_TARGETS += +libcrux_chacha20poly1305::KEY_LEN
LIBCRUX_CHACHA20POLY1305_TARGETS += +libcrux_chacha20poly1305::NONCE_LEN
LIBCRUX_CHACHA20POLY1305_TARGETS += +libcrux_chacha20poly1305::TAG_LEN
LIBCRUX_CURVE25519_TARGETS += +libcrux_curve25519::DK_LEN
LIBCRUX_CURVE25519_TARGETS += +libcrux_curve25519::EK_LEN
LIBCRUX_CURVE25519_TARGETS += +libcrux_curve25519::impl_hacl::ecdh
LIBCRUX_CURVE25519_TARGETS += +libcrux_curve25519::impl_hacl::secret_to_public
LIBCRUX_CURVE25519_TARGETS += +libcrux_curve25519::SS_LEN
LIBCRUX_CURVE25519_TARGETS += +libcrux_curve25519::X25519
LIBCRUX_KEM_TARGETS += +libcrux_kem::Algorithm
LIBCRUX_KEM_TARGETS += +libcrux_kem::Algorithm::MlKem768
LIBCRUX_KEM_TARGETS += +libcrux_kem::Algorithm::X25519
LIBCRUX_KEM_TARGETS += +libcrux_kem::Algorithm::XWingKemDraft06
LIBCRUX_KEM_TARGETS += +libcrux_kem::key_gen
LIBCRUX_KEM_TARGETS += +libcrux_kem::key_gen_derand
LIBCRUX_KEM_TARGETS += +libcrux_kem::PrivateKey
LIBCRUX_KEM_TARGETS += +libcrux_kem::PublicKey
LIBCRUX_ML_KEM_TARGETS += +libcrux_ml_kem::ind_cca::KEY_GENERATION_SEED_SIZE
LIBCRUX_ML_KEM_TARGETS += +libcrux_ml_kem::mlkem768
LIBCRUX_ML_KEM_TARGETS += +libcrux_ml_kem::mlkem768::generate_key_pair
LIBCRUX_ML_KEM_TARGETS += +libcrux_ml_kem::mlkem768::MlKem768
LIBCRUX_TRAITS_TARGETS += +libcrux_traits::kem
LIBCRUX_TRAITS_TARGETS += +libcrux_traits::kem::arrayref
LIBCRUX_TRAITS_TARGETS += +libcrux_traits::kem::arrayref::Kem
LIBCRUX_TRAITS_TARGETS += +libcrux_traits::kem::owned
LIBCRUX_TRAITS_TARGETS += +libcrux_traits::kem::owned::Kem
