# AUTOGENERATED. DO NOT EDIT. Manual edits belong in the Makefile.
# Regenerate with: 'make update-targets'

LIBCRUX_CHACHA20POLY1305_TARGETS += +libcrux_chacha20poly1305::KEY_LEN
LIBCRUX_CHACHA20POLY1305_TARGETS += +libcrux_chacha20poly1305::NONCE_LEN
LIBCRUX_CHACHA20POLY1305_TARGETS += +libcrux_chacha20poly1305::TAG_LEN

LIBCRUX_CURVE25519_TARGETS += +libcrux_curve25519::DK_LEN
LIBCRUX_CURVE25519_TARGETS += +libcrux_curve25519::EK_LEN
LIBCRUX_CURVE25519_TARGETS += +libcrux_curve25519::SS_LEN

LIBCRUX_ECDH_TARGETS += +libcrux_ecdh::Error
LIBCRUX_ECDH_TARGETS += +libcrux_ecdh::*::PrivateKey
LIBCRUX_ECDH_TARGETS += +libcrux_ecdh::*::PublicKey
LIBCRUX_ECDH_TARGETS += +libcrux_ecdh::*::SharedSecret

LIBCRUX_KEM_TARGETS += +libcrux_kem::Algorithm
LIBCRUX_KEM_TARGETS += +libcrux_kem::Ct
LIBCRUX_KEM_TARGETS += +libcrux_kem::Error
LIBCRUX_KEM_TARGETS += +libcrux_kem::PrivateKey
LIBCRUX_KEM_TARGETS += +libcrux_kem::PublicKey
LIBCRUX_KEM_TARGETS += +libcrux_kem::Ss

LIBCRUX_ML_KEM_TARGETS += +libcrux_ml_kem::mlkem768::MlKem768
LIBCRUX_ML_KEM_TARGETS += +libcrux_ml_kem::types::MlKemCiphertext
LIBCRUX_ML_KEM_TARGETS += +libcrux_ml_kem::types::MlKemPrivateKey
LIBCRUX_ML_KEM_TARGETS += +libcrux_ml_kem::types::MlKemPublicKey

LIBCRUX_TRAITS_TARGETS += +libcrux_traits::kem::arrayref::DecapsError
LIBCRUX_TRAITS_TARGETS += +libcrux_traits::kem::arrayref::EncapsError
LIBCRUX_TRAITS_TARGETS += +libcrux_traits::kem::arrayref::Kem
LIBCRUX_TRAITS_TARGETS += +libcrux_traits::kem::arrayref::KeyGenError
LIBCRUX_TRAITS_TARGETS += +libcrux_traits::kem::owned::Kem
