[package]
name = "securedrop-protocol-minimal"
description = "A wip impl of the securedrop protocol"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

# hax extraction for this crate is configured in "Makefile", as documented here:
# https://github.com/freedomofpress/securedrop-protocol/wiki/Verification#how-are-f-modules-extracted-from-protocol-minimal

[lib]

# Note for no_std compat: Don't add rand/getrandom dependencies in core library!
[dependencies]
# hax extraction for dependencies is configured in "proofs/fstar/models/Makefile", as documented
# here:
# https://github.com/freedomofpress/securedrop-protocol/wiki/Verification#how-are-f-interfaces-extracted-from-our-dependencies

# Crypto stack:
hpke-rs = { workspace = true, features = ["libcrux"] }
libcrux-ed25519 = { workspace = true, features = ["rand"] }
libcrux-curve25519.workspace = true
libcrux-chacha20poly1305.workspace = true
libcrux-traits.workspace = true
libcrux-kem.workspace = true
libcrux-ml-kem.workspace = true
libcrux-sha2.workspace = true
libcrux-hkdf.workspace = true

curve25519-dalek = { version = "5.0.0", default-features = false, features = [
    "alloc",
    "precomputed-tables",
    "zeroize",
] }

# Everything else:
anyhow.workspace = true
rand_core.workspace = true
hashbrown = { workspace = true, features = ["raw"] }
uuid = { workspace = true, features = ["v4", "js"] }
bip39 = { workspace = true, features = ["alloc"] }
hex = { workspace = true, features = ["alloc"] }
serde = { workspace = true, features = ["derive", "alloc"] }

# pin an exact version to resolve wasm-bindgen schema compatibility issue
rand_chacha = { workspace = true }

# TODO: getrandom/rand should be removed from the protocol-minimal crate's core dependencies, and a randomness
# source should only be supplied by an architecture-specific consumer crate, but this is blocked
# on https://github.com/celabshq/libcrux/issues/1544, which depends on getrandom 0.4.2.
## for wasm32-unknown-unknown
[target.'cfg(all(target_arch="wasm32", target_os = "unknown"))'.dependencies]
getrandom = { version = "0.4", default-features = false, features = ["wasm_js"] }

[dev-dependencies]
proptest.workspace = true
getrandom.workspace = true
serde_json.workspace = true
criterion.workspace = true
rand.workspace = true

[[bench]]
name = "challenges"
harness = false

[profile.release]
opt-level = "z"     # smallest code size
lto = true
codegen-units = 1
panic = "abort"
strip = true

[target."cfg(hax)".dependencies]
hax-lib.workspace = true

[lints]
workspace = true
